// ****************** Ctest_modelClassFactory.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#ifndef CTEST_MODELCLASSFACTORY_H_INCLUDED
#define CTEST_MODELCLASSFACTORY_H_INCLUDED

#include "ObjClassFactory.h"

class Ctest_modelClassFactory : public CObjClassFactory
{
public:
	Ctest_modelClassFactory();
	
	// ITComClassFactory
	DECLARE_CLASS_MAP()
};

#endif
