// ****************** Ctest_modelClassFactory.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************

#include "stdafx.h"
#pragma hdrstop

#include "Ctest_model.h"
#include "Ctest_modelClassFactory.h"

// ITComClassFactory
BEGIN_CLASS_MAP(Ctest_modelClassFactory)
	CLASS_ENTRY_RT(CID_test_model,SRVNAME_test_model "!Ctest_model", Ctest_model)
END_CLASS_MAP()


Ctest_modelClassFactory::Ctest_modelClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_test_model)); 
}

