// ****************** Ctest_modelDrv.cpp *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#include "TcPch.h"
#pragma hdrstop
#define DEVICE_MAIN

#include "Ctest_modelDrv.h"
#include "Ctest_model.h"
#include "Ctest_modelClassFactory.h"
#include "test_modelVersion.h"

DECLARE_GENERIC_DEVICE(test_modelDRV)
#undef DEVICE_MAIN

IOSTATUS Ctest_modelDrv::OnLoad( )
{
	TRACE(_T("Ctest_modelClassFactory::OnLoad()\n") );
	m_pObjClassFactory = new Ctest_modelClassFactory();

	return IOSTATUS_SUCCESS;
}

VOID Ctest_modelDrv::OnUnLoad( )
{
	delete m_pObjClassFactory;
}

unsigned long _cdecl Ctest_modelDrv::test_model_GetVersion( )
{
	return(0);
}