// ****************** test_modelVersion.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TEST_MODELVERSION_H_INCLUDED
#define TEST_MODELVERSION_H_INCLUDED

////////////////////////////////////////////////////////////////
//  Version Information
////////////////////////////////////////////////////////////////

#define TWINCAT_TARGET_VERSION  1.2.1235
#define MATLAB_RELEASE	"R2018b"

#endif
