// ****************** test_modelServices.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TEST_MODELSERVICES_H_INCLUDED
#define TEST_MODELSERVICES_H_INCLUDED

#define SRVNAME_test_model "test_model"

// TcCOM-ClassId of this module: 3bbbbf53-40ad-420a-8329-a9a2328ba0dd
const   CTCID   CID_test_model    =  {0x3bbbbf53,0x40ad,0x420a,{0x83,0x29,0xa9,0xa2,0x32,0x8b,0xa0,0xdd}};

#endif


