// ****************** test_modelInterfaces.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TEST_MODELINTERFACES_H_INCLUDED
#define TEST_MODELINTERFACES_H_INCLUDED

#include "test_modelServices.h"

// define new interfaces provided by this driver

#endif
