// ****************** test_modelCtrl.h *******************************
// Generated by TwinCAT Target for MATLAB/Simulink (TE1400)
// MATLAB R2018b (win64)
// TwinCAT 3.1.4022
// TwinCAT Target 1.2.1235
// Beckhoff Automation GmbH & Co. KG     (www.beckhoff.com)
// *************************************************************
#ifndef TEST_MODELCTRL_H_INCLUDED
#define TEST_MODELCTRL_H_INCLUDED

#include <atlbase.h>
#include <atlcom.h>

#define Ctest_modelDrvName "test_model"

#include "test_modelResource.h"
#include "test_modelW32.h"
#include "TcPch.h"
#include "Ctest_modelClassFactory.h"
#include "TcOCFCtrlImpl.h"

class Ctest_modelCtrl :		public CComObjectRootEx<CComMultiThreadModel>
							, public CComCoClass<Ctest_modelCtrl, &CLSID_TcRtwDriverCtrl>
							, public ITcRtwDriverCtrl
							, public ITcOCFCtrlImpl<Ctest_modelCtrl, Ctest_modelClassFactory>
{
public:
	Ctest_modelCtrl() : ITcOCFCtrlImpl<Ctest_modelCtrl, Ctest_modelClassFactory>(){}

	virtual ~Ctest_modelCtrl() {}


DECLARE_REGISTRY_RESOURCEID(IDR_test_modelCtrl)
DECLARE_NOT_AGGREGATABLE(Ctest_modelCtrl)

DECLARE_PROTECT_FINAL_CONSTRUCT()

BEGIN_COM_MAP(Ctest_modelCtrl)
	COM_INTERFACE_ENTRY(ITcRtwDriverCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl)
	COM_INTERFACE_ENTRY(ITcCtrl2)
END_COM_MAP()

};

#endif
